insert into questions(ques_id, title, difficulty, optionA, optionB, optionC, optionD, ans, chosen)
values (1,
        'What is a correct syntax to output "Hello World" in Java?',
        'easy',
        'echo "Hello World"',
        'printf("Hello World")',
        'System.error.println("Hello World)',
        'System.out.println("Hello World")',
        3,
        -1)
;

insert into questions(ques_id, title, difficulty, optionA, optionB, optionC, optionD, ans, chosen)
values (2,
        'Java is short for "JavaScript."',
        'easy',
        'True',
        'False',
        'Partially false',
        'Partially True',
        2,
        -1)
;

insert into questions(ques_id, title, difficulty, optionA, optionB, optionC, optionD, ans, chosen)
values (3,
        'How do you insert COMMENTS in Java code?',
        'easy',
        '# This is a comment',
        '/t This is tab',
        '// This is a comment',
        '/* This is a comment',
        3,
        -1)
;

insert into questions(ques_id, title, difficulty, optionA, optionB, optionC, optionD, ans, chosen)
values (4,
        'Which data type is used to create a variable that should store text?',
        'easy',
        'String',
        'long',
        'Char',
        'Both',
        1,
        -1)
;

insert into questions(ques_id, title, difficulty, optionA, optionB, optionC, optionD, ans, chosen)
values (5,
        'How do you create a variable with the numeric value 5?',
        'easy',
        'num x = 5',
        'float x = 5',
        'double x =5',
        'int x = 5',
        4,
        -1)
;

insert into questions(ques_id, title, difficulty, optionA, optionB, optionC, optionD, ans, chosen)
values (6,
        'How do you create a variable with the floating number 2.8?',
        'easy',
        'num x = 2.8',
        'float x = 2.8',
        'double x = 2.8',
        'int x = 2.8',
        2,
        -1)
;

insert into questions(ques_id, title, difficulty, optionA, optionB, optionC, optionD, ans, chosen)
values (7,
        'Which method can be used to find the length of a string?',
        'easy',
        'getSize()',
        'length()',
        'width()',
        'size()',
        2,
        -1)
;

insert into questions(ques_id, title, difficulty, optionA, optionB, optionC, optionD, ans, chosen)
values (8,
        'Which operator is used to add together two values?',
        'easy',
        '&&',
        '.add()',
        '++',
        '+',
        4,
        -1)
;

insert into questions(ques_id, title, difficulty, optionA, optionB, optionC, optionD, ans, chosen)
values (9,
        'The value of a string variable can be surrounded by single quotes.',
        'easy',
        'True',
        'False',
        'partially true',
        'Maybe',
        2,
        -1)
;

insert into questions(ques_id, title, difficulty, optionA, optionB, optionC, optionD, ans, chosen)
values (10,
        'Which operator can be used to compare two values?',
        'easy',
        '><',
        '!=',
        '&|',
        '==',
        4,
        -1)
;
insert into questions(ques_id, title, difficulty, optionA, optionB, optionC, optionD, ans, chosen)
values (11,
        'In java control statements break, continue, return, try-catch-finally and assert belongs to?',
        'easy',
        'Selection statements',
        'Loop Statements',
        'Transfer statements',
        'Pause Statement',
        3,
        -1)
;
insert into questions(ques_id, title, difficulty, optionA, optionB, optionC, optionD, ans, chosen)
values (12,
        'Which provides runtime environment for java byte code to be executed?',
        'easy',
        'JDBK',
        'JVM',
        'JRE',
        'JAVAC',
        2,
        -1)
;
insert into questions(ques_id, title, difficulty, optionA, optionB, optionC, optionD, ans, chosen)
values (13,
        'Which of the following are not Java keywords ?',
        'easy',
        'double',
        'switch',
        'then',
        'instanceof',
        3,
        -1)
;
insert into questions(ques_id, title, difficulty, optionA, optionB, optionC, optionD, ans, chosen)
values (14,
        'Data type long literals are appended by _____',
        'easy',
        'Uppercase',
        'Lowercase',
        'Long',
        'Both A and B',
        4,
        -1)
;

insert into questions(ques_id, title, difficulty, optionA, optionB, optionC, optionD, ans, chosen)
values (15,
        'Java language was initially called as ________',
        'easy',
        'sumatra',
        'j++',
        'Oak',
        'pine',
        3,
        -1)
;
insert into questions(ques_id, title, difficulty, optionA, optionB, optionC, optionD, ans, chosen)
values (16,
        'What is garbage collection in the context of Java?',
        'moderate',
        'Java deletes all unused java files on the system',
        'Memory used by the object with no reference is automatically reclaimed.',
        'The JVM cleans output of Java program with error',
        'Any unused package in a program automatically gets deleted.',
        2,
        -1)
;

insert into questions(ques_id, title, difficulty, optionA, optionB, optionC, optionD, ans, chosen)
values (17,
        'Which of these data types is used by operating system to manage the Recursion in Java?',
        'moderate',
        'Array',
        'Stack',
        'Queue',
        'Tree',
        2,
        -1)
;
insert into questions(ques_id, title, difficulty, optionA, optionB, optionC, optionD, ans, chosen)
values (18,
        'Which of these is not a correct statement?',
        'moderate',
        'A recursive method must have a base case',
        'Recursion always uses stack',
        'Recursive methods are faster that programmers written loop to call the function repeatedly using a stack',
        'Recursion is managed by Java Runtime environment',
        4,
        -1)
;
insert into questions(ques_id, title, difficulty, optionA, optionB, optionC, optionD, ans, chosen)
values (19,
        ' Which of these class is superclass of String and StringBuffer class?',
        'moderate',
        'ava.util',
        'java.lang',
        'ArrayList',
        'None of the mentioned',
        2,
        -1),
       (20,
        ' Which of these method of class String is used to extract a single character from a String object?',
        'moderate',
        'CHARAT()',
        'chatat()',
        'charAt()',
        'ChatAt()',
        3,
        -1),
       (21,
        'Which of these constructors is used to create an empty String object?',
        'moderate',
        'String()',
        'String(void)',
        'String(0)',
        'None of the mentioned',
        1,
        -1),
       (22,
        'Which of the following is not a core interface of Hibernate?',
        'moderate',
        'Configuration',
        'Criteria',
        'SessionManagement',
        'Session',
        3,
        -1),
       (23,
        'Which of these methods are used to register a keyboard event listener?',
        'moderate',
        'KeyListener()',
        'addKistener()',
        'addKeyListener()',
        'eventKeyboardListener()',
        3,
        -1),
       (24,
        'Event class is defined in which of these libraries?',
        'moderate',
        'java.io',
        'java.lang',
        'java.net',
        'java.util',
        4,
        -1),
       (25,
        'Which of these events will be generated if we close an applet’s window?',
        'moderate',
        'ActionEvent',
        'ComponentEvent',
        'AdjustmentEvent',
        'getID()',
        4,
        -1),
       (26,
        'Which of these methods can be used to determine the type of event?',
        'moderate',
        'getSource()',
        'getEvent()',
        'getEventObject()',
        'WindowEvent',
        4,
        -1),
       (27,
        'Which of the following is not an Enterprise Beans type?',
        'moderate',
        'Doubleton',
        'Singleton',
        'Stateful',
        'Stateless',
        1,
        -1),
       (28,
        'Which file separator should be used by MANIFEST file?',
        'moderate',
        '/',
        '\\',
        '–',
        '//',
        1,
        -1),
       (29,
        'Which of the following is not a feature of Beans?',
        'moderate',
        'Introspection',
        'Events',
        'Persistence',
        'Serialization',
        4,
        -1),
       (30,
        'How to specify autowiring by name?',
        'moderate',
        '@Qualifier',
        '@Type',
        '@Constructor',
        '@Name',
        1,
        -1),
       (31,
        'Which of the following is not a kind of exception that is thrown by the JDBC method?',
        'challenging',
        'DataRounding',
        'SQL Exception',
        'DataTruncation',
        'SQL Warning',
        1,
        -1),
       (32,
        'Which of the following option leads to the portability and security of Java?',
        'challenging',
        'The applet makes the Java code secure and portable',
        'Bytecode is executed by JVM',
        'Use of exception handling',
        'Dynamic binding between objects',
        2,
        -1),
       (33,
        'When the ejbRemove method encounters a system problem,it should throw_______',
        'challenging',
        'javax.ejb.NoSuchEntityException',
        'java.ejb.RemoveException',
        'java.ejb.EJBException',
        'javax.ejb.DuplicateKeyException',
        3,
        -1),
       (34,
        'Which of the following is advantage of using JDBC connection pool?',
        'challenging',
        'Better performance',
        'Slow performance',
        'Using more memory',
        'Using less memory',
        1,
        -1),
       (35,
        'Which is responsible for getting a connection to the database?',
        'challenging',
        'Connection',
        'Driver',
        'Statement',
        'ResultSet',
        2,
        -1),
       (36,
        'Thin driver is also known as?',
        'challenging',
        'Type-3 Driver',
        'Type-2 Driver',
        'Type-4 Driver',
        'Type-1 Driver',
        3,
        -1),
       (37,
        'Which of the following is/are steps for the servlet life cycle?',
        'challenging',
        'Servlet class is loaded',
        'Servlet instance is created',
        'init,Service,destroy method is invoked',
        'All of the mentioned',
        4,
        -1),
       (38,
        'Which of the following code is used to get an attribute in a HTTP Session object in servlets?',
        'challenging',
        'session.alterAttribute(String name)',
        'session.updateAttribute(String name)',
        'session.getAttribute(String name)',
        'session.setAttribute(String name)',
        3,
        -1),
       (39,
        'Which of the following code is used to get an attribute in a HTTP Session object in servlets?',
        'challenging',
        'ServletResponse',
        'ServletRequest',
        'Servlet',
        'ServletConfig',
        2,
        -1),
       (40,
        'Which of the following ways to create a servlet?',
        'challenging',
        'Using Servlet Interface',
        'Using GenericServlet class',
        'Using HttpServlet class',
        'All of given',
        4,
        -1),
       (41,
        'Which component is used to compile, debug and execute the java program?',
        'challenging',
        'JIT',
        'JDK',
        'JVM',
        'JRE',
        2,
        -1),
       (42,
        'How constructor can be used for a servlet?',
        'challenging',
        'Initialization and Constructor function',
        'Constructor function',
        'Setup() method',
        'Initialization',
        1,
        -1),
       (43,
        'The hibernate XML configuration file name is?',
        'challenging',
        'hibernate.cfg.xml',
        'hibernate.cg.xml',
        'hibernate.config.xml',
        'None of the mentioned',
        1,
        -1),
       (44,
        'What does the Session object hold?',
        'challenging',
        'Second Level Cache',
        'First Level Cache',
        'Both A & B',
        'None of the mentioned',
        2,
        -1),
       (45,
        'In which file database table configuration is stored?',
        'challenging',
        '.dbm',
        'ora',
        '.sql',
        '.hbm',
        4,
        -1)
;